<header class="page-header">
  <div class="inner-wrap">
    <h1><a href="index.html">合创永安管理平台</a></h1>
    <div id="user-nav" class="navbar navbar-inverse">
      <ul class="nav" style="width: auto; margin: 0px;">
        <li class="dropdown" id="profile-messages" aria-haspopup="true" aria-expanded="false">
          <a title="" href="#" data-toggle="dropdown" class="dropdown-toggle">
            <span class="text">欢迎你，admin</span>&nbsp;
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu" aria-labelledby="profile-messages">
            <li><a href="#"><i class="icon-user"></i> 个人资料</a></li>
            <li class="divider"></li>
            <li><a href="#"><i class="icon-check"></i> 我的任务</a></li>
            <li class="divider"></li>
            <li><a href="login.html"><i class="icon-key"></i> 退出系统</a></li>
          </ul>
        </li>
        <li class="dropdown" id="menu-messages" aria-haspopup="true" aria-expanded="false">
          <a href="#" data-toggle="dropdown" class="dropdown-toggle">
            <span class="text">我的消息</span>&nbsp;
            <span class="label label-warning">4</span>&nbsp; 
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu" aria-labelledby="menu-messages">
            <li><a class="sAdd" title="" href="#"><i class="icon-plus"></i> 新消息</a></li>
            <li class="divider"></li>
            <li><a class="sInbox" title="" href="#"><i class="icon-envelope"></i> 收件箱</a></li>
            <li class="divider"></li>
            <li><a class="sOutbox" title="" href="#"><i class="icon-arrow-up"></i> 发件箱</a></li>
            <li class="divider"></li>
            <li><a class="sTrash" title="" href="#"><i class="icon-trash"></i> 回收站</a></li>
          </ul>
        </li>
        <li class="">
          <a title="" href="#"><span class="text">&nbsp;退出系统</span></a>
        </li>
      </ul>
    </div>  
  </div>
</header>