<div class="slider-menu-wrap">
  <div id="sidebar">
    <div class="sidebar-fold" id="slider-fold"><span class="glyphicon glyphicon-menu-hamburger"></span></div>
    <ul>
      <li class="submenu">
        <a class="menu_a" href='index.html'><i class="glyphicon glyphicon-th"></i><span>在线监测中心</span></a> 
      </li>
      <li class="submenu">
        <a class="menu_a"><i class="glyphicon glyphicon-blackboard"></i><span>设备管理</span></a> 
      </li>
      <li class="submenu">
        <a class="menu_a" href='analysis.html'><i class="glyphicon glyphicon-signal"></i><span>数据分析</span></a> 
      </li>
      <li class="submenu">
        <a class="menu_a"><i class="glyphicon glyphicon-earphone"></i><span>报警</span></a> 
      </li>
      <li class="submenu">
        <a class="menu_a"><i class="glyphicon glyphicon-list-alt"></i><span>报表管理</span></a> 
      </li>
      <li class="submenu">
        <a class="menu_a"><i class="glyphicon glyphicon-calendar"></i><span>日志管理</span></a> 
      </li>
      <li class="submenu">
        <a class="menu_a"><i class="glyphicon glyphicon-user"></i><span>用户管理</span></a> 
      </li>
    </ul>
  </div>
</div>