<!DOCTYPE html>
<html lang="zh-CN">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="renderer" content="webkit">
    <!-- 上述3个meta标签*必须*放在最前面 -->
    <meta name="description" content="">
    <meta name="author" content="">
    <title>首页</title>
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="js/libs/html5shiv.min.js"></script>
      <script src="js/libs/respond.min.js"></script>
    <![endif]-->
</head>
<body>